
---
title: "Wildlife Overpass Review"
author: "Clayton Lamb, Liam Brennan, Emily Chow"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: github_document
---


```{r render, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='hide'}
# library(credentials)
# usethis::create_github_token()
# set_github_pat()

rmarkdown::render(here::here('WildlifeOverpassReview.Rmd'),
                  output_file = "README.md")
```

## Load Data
```{r Load , results='hide', message=FALSE, warning=FALSE}
library(here)
library(tidyverse)
library(sf)
library(readxl)
library(lubridate)
library(mapview)
library(ggmap)
library(raster)
library(stars)
library(velox)
library(hrbrthemes)
library(RColorBrewer)
library(knitr)
library(basemaps)
library(rworldmap)
library(RStoolbox)
library(ggpubr)
library(cowplot)
library(tidylog)
library(janitor)
library(tidymodels)
options(scipen=999)

##load data
df <- read_xlsx(here::here("data","2022-06-23-Clean-Crossing Structure Literature Review Data_Figures.xlsx"),sheet="1-Global (fill this first)")%>%clean_names()
eff.raw <- read_xlsx(here::here("data","2022-06-23-Clean-Crossing Structure Literature Review Data_Figures.xlsx"), sheet="CL_eff")%>%clean_names()
```



## Map
```{r map, fig.height=7, fig.width=7, message=FALSE, warning=FALSE, results='hide'}

##make spatial, keep last check
op <- st_as_sf(df%>%mutate(lat=extract_numeric(lat),
                                                long=extract_numeric(long)),
               coords=c("long", "lat"),
               crs=4326)%>%
    mutate(continent=case_when(country%in%c("U.S.A", "Canada","U.S.A.")~"North America",
                             TRUE~"Europe, Asia, and Oceania"))%>%
  rename(width=estimated_inner_width_m_from_google_earth_in_cases_where_fencing_is_visible_inner_fence_rail_where_visible,
         length=estimated_length_m_headwall_end_to_end_of_physical_structure_often_indicated_by_start_and_stop_of_guard_rail_concreate_metail_edge_of_strcuture,
         lanes=number_of_lanes_spanned,
         year=year_of_build_clean)%>%
  mutate(length=as.numeric(length),
         width=as.numeric(width),
         lanes=as.numeric(lanes))

               
mapview(op)

world_sf <- st_as_sf(getMap(resolution = "low"))%>%
  st_transform_proj(world_sf, crs = "+proj=wintri")

grat_wintri <- 
  st_graticule(lat = c(-89.9, seq(-80, 80, 20), 89.9)) %>%
  st_transform_proj(crs = "+proj=wintri")

# vectors of latitudes and longitudes that go once around the 
# globe in 1-degree steps
lats <- c(90:-90, -90:90, 90)
longs <- c(rep(c(180, -180), each = 181), 180)

# turn into correctly projected sf collection
wintri_outline <- 
  list(cbind(longs, lats)) %>%
  st_polygon() %>%
  st_sfc( # create sf geometry list column
    crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
  ) %>% 
  st_sf() %>%
  st_transform_proj(crs = "+proj=wintri") # transform to Winkel tripel



ggplot() + 
  geom_sf(data = wintri_outline, fill = "#56B4E950", color = NA) +
  geom_sf(data = grat_wintri, color = "gray10", size = 0.25/.pt, alpha=0.5) + 
  geom_sf(data = world_sf, color = "gray60", size = 0.5/.pt) +
  geom_sf(data = wintri_outline, fill = NA, color = "grey30", size = 0.5/.pt, alpha=0.5) +
  geom_sf(data=op%>%
  st_transform_proj(crs = "+proj=wintri"), size = 2/.pt, color="red")+
  coord_sf(datum = NULL)+
  theme_map()

ggsave(here::here("output","world_map.png"), height=4, width=7, unit="in", bg="white")


#prep basemap
register_google("AIzaSyCOwGx2D77XOqRgGhKmcb5F4Kt_S61tCLI")
#set_defaults(map_service = "osm", map_type = "terrain_bg")

##GLOBAL
bb = st_bbox(c(xmin = -185, xmax = 185, ymax = 85, ymin = -85), crs = st_crs(4326))

bb_ll = st_bbox(
  st_transform(
    st_as_sfc(bb), 
    3857
  )
)

a <- basemap_raster(bb_ll, map_type = "terrain_bg")

a <- a%>%projectRaster(crs="+proj=wintri")
writeRaster(a,here::here("data","basemap.tif"), overwrite=TRUE)
a <- brick(here::here("data","basemap.tif"))%>%
  mask(wintri_outline)

world <- getMap(resolution = "high")
world <- st_as_sf(world)

world <-ggRGB(a, r=1, g=2, b=3)+
  geom_sf(data=op%>%
  st_transform_proj(crs = "+proj=wintri"), size = 2/.pt, color="red")+
  coord_sf(datum = NULL)+
  theme_map()

##W-NA
bb = st_bbox(c(xmin = -137, xmax = -93, ymax = 55, ymin = 28), crs = st_crs(4326))

bb_ll = st_bbox(
  st_transform(
    st_as_sfc(bb), 
    3857
  )
)

bb_clip=st_bbox(c(xmin = -12.5E6, xmax = -10.3E6, ymin = 3.4E6, ymax = 6.4E6), crs = "+proj=wintri")

a <- basemap_raster(bb_ll, map_type = "terrain_bg")
a <- a%>%projectRaster(crs="+proj=wintri")%>%
  raster::crop(bb_clip%>%extent)
writeRaster(a,here::here("data","basemap.tif"), overwrite=TRUE)
a <- brick(here::here("data","basemap.tif"))%>%
  mask(wintri_outline)

WNA <- ggRGB(a, r=1, g=2, b=3)+
  geom_sf(data=op%>%filter(continent=="North America")%>%st_transform_proj(crs = "+proj=wintri")%>%st_intersection(bb_clip%>%st_as_sfc),
          size = 5/.pt, color="red")+
  coord_sf(datum = "+proj=wintri")+
  theme_map()



##Europe
bb = st_bbox(c(xmin = 2, xmax = 24, ymax = 58, ymin = 43), crs = st_crs(4326))

bb_ll = st_bbox(
  st_transform(
    st_as_sfc(bb),
    3857
  )
)

bb_clip=st_bbox(c(xmin = 0.2E6, xmax = 2.2E6, ymin = 4.4E6, ymax = 6.1E6), crs = "+proj=wintri")

a <- basemap_raster(bb_ll, map_type = "terrain_bg")
a <- a%>%projectRaster(crs="+proj=wintri")%>%
  raster::crop(bb_clip%>%extent)
writeRaster(a,here::here("data","basemap.tif"), overwrite=TRUE)
a <- brick(here::here("data","basemap.tif"))%>%
  mask(wintri_outline)

EU <- ggRGB(a, r=1, g=2, b=3)+
  geom_sf(data=op%>%filter(continent!="North America")%>%st_transform_proj(crs = "+proj=wintri")%>%st_intersection(bb_clip%>%st_as_sfc),
          size = 5/.pt, color="red")+
  coord_sf(datum = "+proj=wintri")+
  theme_map()


plot_grid(world,plot_grid(WNA, EU, labels = c("B","C"), rel_widths = c(1, 1.9)), labels = c("A",NA),nrow=2, rel_heights = c(1.9,1))

ggsave(here::here("output","map.png"), height=7, width=7, unit="in", bg="white")


```



## Plots
```{r plots, fig.height=7, fig.width=7, message=FALSE, warning=FALSE, results='hide'}
##clean up column names
plot.dat <- op%>%
  tibble%>%
  dplyr::select(continent,
                year,
                `Width (m)`=width,
                `Length (m)`=length,
                lanes)%>%
    mutate(`Width:length ratio`=`Width (m)`/`Length (m)`)%>%
  tidyr::pivot_longer(`Width (m)`:`Width:length ratio`)%>%
  mutate(name=fct_relevel(name,"Length (m)","Width (m)","Width:length ratio", "lanes"))

plot.dat%>%
  filter(!name%in%"lanes")%>%
  ggplot(aes(y=value))+
    geom_boxplot(fill="grey")+
    facet_wrap(vars(name), scales="free_y")+
  theme_ipsum()+
     theme(axis.title.x = element_text(size=17),
          axis.title.y = element_text(size=17),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size=13),
          plot.title = element_text(size=22),
          plot.subtitle = element_text(size=17),
          legend.position = "none")+
  labs(title="Overpass dimensions",y="")
ggsave(here::here("output", "op_dims.png"), height=6, width=7, unit="in",bg="white")

plot.dat%>%
    filter(!name%in%"lanes")%>%
  ggplot(aes(y=value, fill=name))+
    geom_boxplot()+
    facet_grid(name~continent, scales="free_y")+
  theme_ipsum()+
     theme(axis.title.x = element_text(size=17),
          axis.title.y = element_text(size=17),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size=13),
          plot.title = element_text(size=22),
          plot.subtitle = element_text(size=17),
          legend.position = "none")+
  labs(title="Overpass dimensions",y="")
ggsave(here::here("output", "op_dims_continent.png"), height=10, width=7, unit="in",bg="white")


by.year <- plot.dat%>%
      filter(name%in%"Width (m)")%>%
drop_na(year)%>%
  ggplot(aes(y=value, x=`year`))+
  geom_point()+
  theme_ipsum()+
      facet_wrap(vars(continent))+
     theme(axis.title.x = element_text(size=17),
          axis.title.y = element_text(size=17),
          axis.text = element_text(size=13),
          plot.title = element_text(size=22),
          plot.subtitle = element_text(size=17),
          legend.position = "none")+
  labs(title="Width through time",y="Width (m)", x="Year built")

plot.dat%>%
      filter(name%in%"Width (m)")%>%
      drop_na(year)%>%
  lm(value~year+ continent, data=.)%>%
  summary

by.size <- op%>%
drop_na(approx_size)%>%
  mutate(approx_size=fct_relevel(approx_size,"Small (<50 lbs)","Medium (50-350 lbs)","Large (>350 lbs)"))%>%
  ggplot(aes(y=width, x=approx_size))+
    geom_boxplot(fill="grey")+
  theme_ipsum()+
     theme(axis.title.x = element_text(size=17),
          axis.title.y = element_text(size=17),
          axis.text = element_text(size=13),
          plot.title = element_text(size=22),
          plot.subtitle = element_text(size=17),
          legend.position = "none")+
  labs(title="Width varies by target species",y="Width (m)", x="Target species body size")

ggarrange(by.size,by.year, labels="AUTO", ncol=1)
ggsave(here::here("output", "op_dims_bodysize_year.png"), height=10, width=7, unit="in",bg="white")

op%>%
drop_na(approx_size)%>%
  mutate(approx_size=fct_relevel(approx_size,"Small (<50 lbs)","Medium (50-350 lbs)","Large (>350 lbs)"))%>%
  lm(width~approx_size, data=.)%>%
  summary

```


## Summary stats
```{r stats, fig.height=7, fig.width=7, message=FALSE, warning=FALSE}
plot.dat%>%
  group_by(name) %>%
  summarise(mean = mean(value, na.rm = TRUE),
            min = min(value, na.rm = TRUE),
            max = max(value, na.rm = TRUE),
            n=n())%>%
  kable

plot.dat%>%
  group_by(continent, name) %>%
  summarise(mean = mean(value, na.rm = TRUE),
            min = min(value, na.rm = TRUE),
            max = max(value, na.rm = TRUE),
            n=n())%>%
  kable


op%>%
  drop_na(year)%>%
  mutate(period=case_when(year<2010~"before",
                          year>=2010~"after"))%>%
  group_by(period) %>%
  summarise(W = mean(width, na.rm = TRUE),
            L=mean(length, na.rm = TRUE),
            n=n())%>%
  kable
```

## Effectiveness
```{r Effectiveness, fig.height=7, fig.width=7, message=FALSE, warning=FALSE}
eff <- eff.raw%>%
    rename(`Width (m)`=estimated_inner_width_m_from_google_earth_in_cases_where_fencing_is_visible_inner_fence_rail_where_visible,
         `Length (m)`=estimated_length_m_headwall_end_to_end_of_physical_structure_often_indicated_by_start_and_stop_of_guard_rail_concreate_metail_edge_of_strcuture,
         )%>%
  mutate(`Length (m)`=as.numeric(`Length (m)`),
         `Width (m)`=as.numeric(`Width (m)`),
         `W:L ratio`=`Width (m)`/`Length (m)`)%>%
  dplyr::select(crossing=name_if_applicable,`Width (m)`,`W:L ratio`,days=approximate_number_of_monitoring_days, total:coyote)%>%
  dplyr::select(-big_horned_sheep)%>% ##not enough structures near sheep range to test
  pivot_longer(total:coyote)%>%
  mutate(rate=(value/days)*30,
         name=str_replace_all(name,"_"," "))
  
###plot
eff%>%
  filter(name%in%"total")%>%
  dplyr::select(crossing, rate, `Width (m)`,`W:L ratio`)%>%
  pivot_longer(`Width (m)`:`W:L ratio`)%>%
  ggplot(aes(y=rate, x=value, fill=name))+
    facet_wrap(vars(name), scales="free_x")+
  theme_ipsum()+
  geom_smooth(method="lm",se=FALSE, color="black", linetype="dashed")+
        geom_point(alpha=0.5)+
     theme(axis.title.x = element_text(size=17),
          axis.title.y = element_text(size=17),
          axis.text.x = element_text(size=17),
          axis.text.y = element_text(size=13),
          plot.title = element_text(size=22),
          plot.subtitle = element_text(size=17),
          legend.position = "none")+
  labs(title="Overpass dimensions",y="Crossings per month",x="")
ggsave(here::here("output", "op_dims_effectiveness.png"), height=5, width=7, unit="in",bg="white")


###Stats
##total
eff%>%
  filter(name%in%"total")%>%
  dplyr::select(crossing, rate, `Width (m)`,`W:L ratio`)%>%
  pivot_longer(`Width (m)`:`W:L ratio`)%>%
  nest(data = c(-name))%>% 
  mutate(
    fit = map(data, ~ lm(rate ~ value, data = .x)),
    tidied = map(fit, tidy)
  ) %>% 
  unnest(tidied) %>% 
  dplyr::select(-data, -fit)%>%
  filter(term=="value")%>%
  mutate_if(is.numeric, round, 5)%>%
  kable

##summarise total across lengths
eff%>%
  dplyr::select(crossing, rate, `Width (m)`)%>%
  mutate(width.bin=case_when(`Width (m)`<=40~"<=40",
                             `Width (m)`>40~">40"))%>%
  drop_na(width.bin)%>%
   lm(rate ~ width.bin, data=.)%>%
  tidy%>%
  kable

eff%>%
  dplyr::select(crossing, rate, `Width (m)`)%>%
  mutate(width.bin=case_when(`Width (m)`<=40~"<=40",
                             `Width (m)`>40~">40"))%>%
  drop_na(width.bin)%>%
  group_by(width.bin)%>%
  summarise(mean=mean(rate, na.rm=TRUE),
            se=sd(rate, na.rm=TRUE)/sqrt(n()))

##by species

eff%>%
  filter(!name%in%"total")%>%
  dplyr::select(crossing, rate, `Width (m)`,name)%>%
  ggplot(aes(y=rate, x=`Width (m)`, fill=name))+
    facet_wrap(vars(name), scales="free_y")+
  theme_ipsum()+
  geom_smooth(method="lm",se=FALSE, color="black", linetype="dashed")+
      geom_point(alpha=0.5)+
     theme(axis.title.x = element_text(size=17),
          axis.title.y = element_text(size=17),
          axis.text.x = element_text(size=17),
          axis.text.y = element_text(size=13),
          plot.title = element_text(size=22),
          plot.subtitle = element_text(size=17),
          legend.position = "none")+
  labs(title="Overpass dimensions",y="Crossings per month",x="")

ggsave(here::here("output", "op_dims_effectiveness_byspecies.png"), height=8, width=10, unit="in",bg="white")


##length
length.by.sp <- eff%>%
  filter(!name%in%"total")%>%
  dplyr::select(crossing, rate,name, `Width (m)`)%>%
  nest(data = c(-name))%>% 
  mutate(
    fit = map(data, ~ lm(rate ~ `Width (m)`, data = .x)),
    tidied = map(fit, tidy)
  ) %>% 
  unnest(tidied) %>% 
  dplyr::select(-data, -fit)%>%
  filter(term!="(Intercept)")%>%
  mutate_if(is.numeric, round, 5)%>%
  kable



eff%>%
  filter(!name%in%"total")%>%
  dplyr::select(crossing, rate,name, `Width (m)`)%>%
  group_by(name)%>%
  mutate(rate_scale=scale(rate))%>%
  ungroup%>%
  nest(data = c(-name))%>% 
  mutate(
    fit = map(data, ~ lm(rate_scale ~ `Width (m)`, data = .x)),
    tidied = map(fit, tidy)
  ) %>% 
  unnest(tidied) %>% 
  dplyr::select(-data, -fit)%>%
  filter(term!="(Intercept)")%>%
  mutate_if(is.numeric, round, 5)%>%
  ggplot(aes(x=estimate, xmin=estimate-std.error,xmax=estimate+std.error,y=name))+
  geom_point()+
  geom_linerange()+
  theme_ipsum()+
  geom_vline(xintercept=0, linetype="dashed")+
       theme(axis.title.x = element_text(size=17),
          axis.title.y = element_text(size=17),
          axis.text.x = element_text(size=17),
          axis.text.y = element_text(size=13),
          plot.title = element_text(size=22),
          plot.subtitle = element_text(size=17),
          legend.position = "none")+
  labs(title="",y="Species",x="Effect of width on crossings (standardized)")
  

##summarise  across lengths
eff%>%
  filter(!name%in%"total")%>%
  dplyr::select(crossing, rate,name,name, `Width (m)`)%>%
  mutate(width.bin=case_when(`Width (m)`<=40~"<=40",
                             `Width (m)`>40~">40"))%>%
  drop_na(width.bin)%>%
  nest(data = c(-name))%>% 
  mutate(
    fit = map(data, ~ lm(rate ~ width.bin, data = .x)),
    tidied = map(fit, tidy)
  ) %>% 
  unnest(tidied) %>% 
  dplyr::select(-data, -fit)%>%
  filter(term!="(Intercept)")%>%
  mutate_if(is.numeric, round, 5)%>%
  kable



##Width:length
eff%>%
  filter(!name%in%"total")%>%
  dplyr::select(crossing, rate,name, `W:L ratio`)%>%
  nest(data = c(-name))%>% 
  mutate(
    fit = map(data, ~ lm(rate ~ `W:L ratio`, data = .x)),
    tidied = map(fit, tidy)
  ) %>% 
  unnest(tidied) %>% 
  dplyr::select(-data, -fit)%>%
  filter(term!="(Intercept)")%>%
  mutate_if(is.numeric, round, 5)%>%
  kable

```
